name: Build & Test

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src/

    - name: Build
      run: dotnet build --no-restore
      working-directory: src/

    - name: Create dotnet manifest
      run: dotnet new tool-manifest
      working-directory: src/
    
    - name: Install Swashbuckle
      run: dotnet tool install SwashBuckle.AspNetCore.Cli
      working-directory: src/
    
    - name: Generate Open API documentation
      run: dotnet swagger tofile --output ./swagger.json AzureIoTHub.Portal/Server/bin/Debug/net6.0/AzureIoTHub.Portal.Server.dll v1
      working-directory: src/
    
    # Upload swagger docs to GitHub
    - uses: actions/upload-artifact@v2
      if: success()
      with:
        name: swagger-doc
        path: ./src/swagger.json

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal --logger trx --collect:"XPlat Code Coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura AzureIoTHub.Portal.Server.Tests/AzureIoTHub.Portal.Server.Tests.csproj
      working-directory: src/

    # Upload test results as artifact
    - uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: test-results
        path: |
          src/AzureIoTHub.Portal.Server.Tests/TestResults

    - name: Upload to Codecov test reports
      uses: codecov/codecov-action@v2
      with:
        directory: src/AzureIoTHub.Portal.Server.Tests/TestResults

  add-openapi-docs: 
    name: Import OpenAPI to documentation
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: 'docs/main'

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Install widdershins
        run: npm install -g widdershins

      - uses: actions/download-artifact@v2
        with:
          name: swagger-doc

      - name: Generate Open API Markdown
        run: widdershins --environment widdershins.json swagger.json -o open-api.md

      - name: Push Open API Markdown to GitHub
        uses: actions-js/push@master
        with:
          branch: 'docs/main'
          message: 'Adds auto-generated Open API doc'
          github_token: ${{ secrets.GITHUB_TOKEN }}

