name: Build & Test

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main, v3/main ]
  push:
    branches: [ main, v3/main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.3.0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dotnet tools
      run: dotnet tool restore
      working-directory: src/
      
    - name: Restore dependencies
      run: dotnet restore AzureIoTHub.Portal.sln 
      working-directory: src/

    - name: Build
      run: dotnet build AzureIoTHub.Portal.sln --no-restore -p:ClientAssetsRestoreCommand="npm ci"
      working-directory: src/
    
    - name: Generate Open API documentation
      run: dotnet swagger tofile --output ./swagger.json AzureIoTHub.Portal.Server/bin/Debug/net7.0/AzureIoTHub.Portal.Server.dll v1
      working-directory: src/
    
    # Upload swagger docs to GitHub
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: swagger-doc
        path: ./src/swagger.json

    - name: Run E2E tests
      run: dotnet test --no-build AzureIoTHub.Portal.Tests.E2E.csproj
      working-directory: src/
